# Generated by Django 3.2.8 on 2021-11-26 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aloqa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('massage', models.TextField(default=0)),
                ('number', models.IntegerField()),
                ('address', models.CharField(max_length=300)),
            ],
        ),
    ]
