# Generated by Django 2.2.16 on 2021-12-17 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20211217_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carditem',
            name='food',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='carditems', to='product.Food'),
        ),
    ]
