# Generated by Django 2.2.16 on 2021-12-18 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20211217_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carditem',
            name='food',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='carditems', to='product.Food'),
        ),
        migrations.AlterField(
            model_name='food',
            name='rasmi',
            field=models.TextField(max_length=300),
        ),
    ]
